### ISSUE TITLE
Memory Maximum voltage read over minimum voltage

### ISSUE THREAD

**Issue by stanislavpetkov** [brunexgeek/smbios-parser#1]
Hello,

There is a mistake in smbios.cc 
// 2.8+
        if (version_ >= smbios::SMBIOS_2_8)
        {
            entry_.data.memory.MinimumVoltage = DMI_READ_16U;
            entry_.data.memory.MinimumVoltage = DMI_READ_16U;
            entry_.data.memory.ConfiguredVoltage = DMI_READ_16U;
        }

should be replaced with

// 2.8+
        if (version_ >= smbios::SMBIOS_2_8)
        {
            entry_.data.memory.MinimumVoltage = DMI_READ_16U;
            entry_.data.memory.MaximumVoltage = DMI_READ_16U;
            entry_.data.memory.ConfiguredVoltage = DMI_READ_16U;
        }

Have a nice day

**Comment by brunexgeek** [comment]
A "little" late in my response, but thanks! Problem fixed.
