### ISSUE TITLE
Incorrect SMBIOS version check

### ISSUE THREAD

**Issue by Immortalety** [brunexgeek/smbios-parser#16]
This macro checks the SMBIOS version, but for example I have version 3.3 and it fails with an error. There was no such problem in previous versions of the library.

https://github.com/brunexgeek/smbios-parser/blob/75c24b7c6a1cbf74afac7225d850db6aeed6e938/smbios.c#L21

![image](https://github.com/user-attachments/assets/80015292-51a1-4a62-b7dd-9716748641f6)

**Comment by alexv-ds** [comment]
+++

**Comment by brunexgeek** [comment]
Thanks for reporting the problem. The way it's implemented now will definitely return an error for versions above ` 3.0` .

**Comment by brunexgeek** [comment]
@Immortalety I merged a fix for the SMBIOS validation into `master`. Could you try it and see if it solves your issue?

**Comment by Immortalety** [comment]
> @Immortalety I merged a fix for the SMBIOS validation into `master`. Could you try it and see if it solves your issue?

Yes, this problem has been solved now. Thank you for your work!
