### ISSUE TITLE
Undefined macro

### ISSUE THREAD

**Issue by Immortalety** [brunexgeek/smbios-parser#18]
If the library is added to the project by copying files, the compiler throws errors, because `SMBIOS_EXPORT` is used in the definition of functions, but it is not defined.

https://github.com/brunexgeek/smbios-parser/blob/163b9ca0f5e2017bcc0286cfe5d21554c5c330e1/smbios.h#L31-L38

**Comment by brunexgeek** [comment]
I added an `#else` to ensure `SMBIOS_EXPORT` is defined (commit 64e8964).
